///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("a64524be-86c0-4f43-8300-08f1a1e63ac3", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            Usuario = "lmattioli";
            Contrasenia = "silverarrow";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _Usuario;

        /// <summary>
        /// Gets or sets the value of variable Usuario.
        /// </summary>
        [TestVariable("4706f1ff-a560-453b-a6c9-642422385362")]
        public string Usuario
        {
            get { return _Usuario; }
            set { _Usuario = value; }
        }

        string _Contrasenia;

        /// <summary>
        /// Gets or sets the value of variable Contrasenia.
        /// </summary>
        [TestVariable("7e77cef4-fd01-48c3-9ebe-6fd0e02c47fd")]
        public string Contrasenia
        {
            get { return _Contrasenia; }
            set { _Contrasenia = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // **** Ingreso de usuario y clave ****
            Report.Log(ReportLevel.Info, "Section", "**** Ingreso de usuario y clave ****", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Usuario' on item 'SURA.txtbox_Usuario'.", repo.SURA.txtbox_UsuarioInfo, new RecordItemIndex(1));
            repo.SURA.txtbox_Usuario.Element.SetAttributeValue("TagValue", Usuario);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Contrasenia' on item 'SURA.txtbox_Contrasenia'.", repo.SURA.txtbox_ContraseniaInfo, new RecordItemIndex(2));
            repo.SURA.txtbox_Contrasenia.Element.SetAttributeValue("TagValue", Contrasenia);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.bttn_IniciarSesion' at 26;3.", repo.SURA.bttn_IniciarSesionInfo, new RecordItemIndex(3));
            repo.SURA.bttn_IniciarSesion.Click("26;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.bttn_Configuracion'", repo.SURA.bttn_ConfiguracionInfo, new ActionTimeout(20000), new RecordItemIndex(4));
            repo.SURA.bttn_ConfiguracionInfo.WaitForExists(20000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
