///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Generales
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AnulaPoliza recording.
    /// </summary>
    [TestModule("de114023-b9f4-4177-8d8a-d559886158ae", ModuleType.Recording, 1)]
    public partial class AnulaPoliza : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static AnulaPoliza instance = new AnulaPoliza();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AnulaPoliza()
        {
            NumeroTransaccion = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AnulaPoliza Instance
        {
            get { return instance; }
        }

#region Variables

        string _NumeroTransaccion;

        /// <summary>
        /// Gets or sets the value of variable NumeroTransaccion.
        /// </summary>
        [TestVariable("f430b997-66e5-4e02-a12f-df64d9e529a0")]
        public string NumeroTransaccion
        {
            get { return _NumeroTransaccion; }
            set { _NumeroTransaccion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.bttn_Nuevo' at Center.", repo.SURA.Anulacion_Rehabilitacion.bttn_NuevoInfo, new RecordItemIndex(0));
            repo.SURA.Anulacion_Rehabilitacion.bttn_Nuevo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.bttn_AnularPoliza' at Center.", repo.SURA.Anulacion_Rehabilitacion.bttn_AnularPolizaInfo, new RecordItemIndex(1));
            repo.SURA.Anulacion_Rehabilitacion.bttn_AnularPoliza.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.txt_IniciarAnulacion'", repo.SURA.Anulacion_Rehabilitacion.txt_IniciarAnulacionInfo, new ActionTimeout(20000), new RecordItemIndex(2));
            repo.SURA.Anulacion_Rehabilitacion.txt_IniciarAnulacionInfo.WaitForExists(20000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.txtbox_Fuente' at Center.", repo.SURA.Anulacion_Rehabilitacion.txtbox_FuenteInfo, new RecordItemIndex(3));
            repo.SURA.Anulacion_Rehabilitacion.txtbox_Fuente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.option_Asegurado'", repo.SURA.Anulacion_Rehabilitacion.option_AseguradoInfo, new ActionTimeout(5000), new RecordItemIndex(4));
            repo.SURA.Anulacion_Rehabilitacion.option_AseguradoInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.option_Asegurado' at Center.", repo.SURA.Anulacion_Rehabilitacion.option_AseguradoInfo, new RecordItemIndex(5));
            repo.SURA.Anulacion_Rehabilitacion.option_Asegurado.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.Copy_of_txtbox_Fuente'", repo.SURA.Anulacion_Rehabilitacion.Copy_of_txtbox_FuenteInfo, new ActionTimeout(10000), new RecordItemIndex(6));
            repo.SURA.Anulacion_Rehabilitacion.Copy_of_txtbox_FuenteInfo.WaitForNotExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.txtbox_Motivo' at Center.", repo.SURA.Anulacion_Rehabilitacion.txtbox_MotivoInfo, new RecordItemIndex(7));
            repo.SURA.Anulacion_Rehabilitacion.txtbox_Motivo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 7s to exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.option_AnulacionPorDesistimiento'", repo.SURA.Anulacion_Rehabilitacion.option_AnulacionPorDesistimientoInfo, new ActionTimeout(7000), new RecordItemIndex(8));
            repo.SURA.Anulacion_Rehabilitacion.option_AnulacionPorDesistimientoInfo.WaitForExists(7000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Anulacion_Rehabilitacion.option_AnulacionPorDesistimiento' at Center.", repo.SURA.Anulacion_Rehabilitacion.option_AnulacionPorDesistimientoInfo, new RecordItemIndex(9));
            repo.SURA.Anulacion_Rehabilitacion.option_AnulacionPorDesistimiento.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.Anulacion_Rehabilitacion.Copy_of_txtbox_Motivo'", repo.SURA.Anulacion_Rehabilitacion.Copy_of_txtbox_MotivoInfo, new ActionTimeout(10000), new RecordItemIndex(10));
            repo.SURA.Anulacion_Rehabilitacion.Copy_of_txtbox_MotivoInfo.WaitForNotExists(10000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.bttn_IniciarAnulacion' at Center.", repo.ApplicationUnderTest.bttn_IniciarAnulacionInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.bttn_IniciarAnulacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 40s to exist. Associated repository item: 'ApplicationUnderTest.txt_Confirmacion'", repo.ApplicationUnderTest.txt_ConfirmacionInfo, new ActionTimeout(40000), new RecordItemIndex(13));
            repo.ApplicationUnderTest.txt_ConfirmacionInfo.WaitForExists(40000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.bttn_AnularAhora' at Center.", repo.ApplicationUnderTest.bttn_AnularAhoraInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.bttn_AnularAhora.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.bttn_Aceptar' at Center.", repo.ApplicationUnderTest.bttn_AceptarInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.bttn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Anulación Contratada') on item 'ApplicationUnderTest.txt_AnulacionContratada'.", repo.ApplicationUnderTest.txt_AnulacionContratadaInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.ApplicationUnderTest.txt_AnulacionContratadaInfo, "InnerText", "Anulación Contratada");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.txt_NroAnulacion' and assigning the part of its value captured by '[0-9]{10}' to variable 'NumeroTransaccion'.", repo.ApplicationUnderTest.txt_NroAnulacionInfo, new RecordItemIndex(18));
            NumeroTransaccion = repo.ApplicationUnderTest.txt_NroAnulacion.Element.GetAttributeValueText("InnerText", new Regex("[0-9]{10}"));
            Delay.Milliseconds(0);
            
            // El número de transacción es
            Report.Log(ReportLevel.Info, "Section", "El número de transacción es", new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "User", NumeroTransaccion, new RecordItemIndex(20));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
