///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Generales
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscarPolizaReversa recording.
    /// </summary>
    [TestModule("b4735cf6-9c63-407c-9248-f7233b2caf44", ModuleType.Recording, 1)]
    public partial class BuscarPolizaReversa : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static BuscarPolizaReversa instance = new BuscarPolizaReversa();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscarPolizaReversa()
        {
            NUMPOLIZA_REVERTIR = "11111003253";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscarPolizaReversa Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NUMPOLIZA_REVERTIR.
        /// </summary>
        [TestVariable("e5f0bc49-df2f-4a9e-ad72-f6f872184117")]
        public string NUMPOLIZA_REVERTIR
        {
            get { return repo.NUMPOLIZA_REVERTIR; }
            set { repo.NUMPOLIZA_REVERTIR = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '' on item 'SURA.txt_NumPolizaBC'.", repo.SURA.txt_NumPolizaBCInfo, new RecordItemIndex(0));
            repo.SURA.txt_NumPolizaBC.Element.SetAttributeValue("Value", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NUMPOLIZA_REVERTIR' with focus on 'SURA.txt_NumPolizaBC'.", repo.SURA.txt_NumPolizaBCInfo, new RecordItemIndex(1));
            repo.SURA.txt_NumPolizaBC.PressKeys(NUMPOLIZA_REVERTIR);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(2));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
