///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Generales
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConsultarLocalidades recording.
    /// </summary>
    [TestModule("fa32e596-1d6d-496d-a93e-30f41b87972f", ModuleType.Recording, 1)]
    public partial class ConsultarLocalidades : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static ConsultarLocalidades instance = new ConsultarLocalidades();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConsultarLocalidades()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConsultarLocalidades Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.FlechitaProvinciaCM' at Center.", repo.SURA.FlechitaProvinciaCMInfo, new RecordItemIndex(0));
            repo.SURA.FlechitaProvinciaCM.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Copy_of_SelectPrimerItem' at Center.", repo.SURA.Copy_of_SelectPrimerItemInfo, new RecordItemIndex(1));
            repo.SURA.Copy_of_SelectPrimerItem.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.Copy_of_FlechitaProvinciaCM'", repo.SURA.Copy_of_FlechitaProvinciaCMInfo, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.SURA.Copy_of_FlechitaProvinciaCMInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.FlechitaLocalidadesCM' at Center.", repo.SURA.FlechitaLocalidadesCMInfo, new RecordItemIndex(3));
            repo.SURA.FlechitaLocalidadesCM.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Copy_of_SelectPrimerItem' at Center.", repo.SURA.Copy_of_SelectPrimerItemInfo, new RecordItemIndex(4));
            repo.SURA.Copy_of_SelectPrimerItem.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SURA.Copy_of_FlechitaLocalidadesCM'", repo.SURA.Copy_of_FlechitaLocalidadesCMInfo, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SURA.Copy_of_FlechitaLocalidadesCMInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.CodigoPostalCM'", repo.SURA.CodigoPostalCMInfo, new ActionTimeout(30000), new RecordItemIndex(6));
            repo.SURA.CodigoPostalCMInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(7));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
