///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Generales
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PasoParametroCSV recording.
    /// </summary>
    [TestModule("c668a664-b489-4838-92b2-32bde3db896a", ModuleType.Recording, 1)]
    public partial class PasoParametroCSV : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static PasoParametroCSV instance = new PasoParametroCSV();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PasoParametroCSV()
        {
            NroCuenta_CSV = "12345";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PasoParametroCSV Instance
        {
            get { return instance; }
        }

#region Variables

        string _NroCuenta_CSV;

        /// <summary>
        /// Gets or sets the value of variable NroCuenta_CSV.
        /// </summary>
        [TestVariable("79d668a6-0859-4bb6-ac72-40293e87454d")]
        public string NroCuenta_CSV
        {
            get { return _NroCuenta_CSV; }
            set { _NroCuenta_CSV = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            PasaParametroCSV();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
