///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscaPolizaParaAnular recording.
    /// </summary>
    [TestModule("097746c6-29dd-498f-9b4e-0874387cbb2e", ModuleType.Recording, 1)]
    public partial class BuscaPolizaParaAnular : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static BuscaPolizaParaAnular instance = new BuscaPolizaParaAnular();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscaPolizaParaAnular()
        {
            NumPoliza = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscaPolizaParaAnular Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NumPoliza.
        /// </summary>
        [TestVariable("7d638e27-b74a-4929-9ff9-737a7d9cd1ac")]
        public string NumPoliza
        {
            get { return repo.NumPoliza; }
            set { repo.NumPoliza = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.bttn_MenuPoliza' at CenterRight.", repo.ApplicationUnderTest.bttn_MenuPolizaInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.bttn_MenuPoliza.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txtbox_NumPoliza' at Center.", repo.ApplicationUnderTest.txtbox_NumPolizaInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.txtbox_NumPoliza.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NumPoliza' with focus on 'ApplicationUnderTest.txtbox_NumPoliza'.", repo.ApplicationUnderTest.txtbox_NumPolizaInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.txtbox_NumPoliza.PressKeys(NumPoliza);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.txtbox_NumPoliza'.", repo.ApplicationUnderTest.txtbox_NumPolizaInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.txtbox_NumPoliza.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.txt_InformacionDePoliza'", repo.ApplicationUnderTest.txt_InformacionDePolizaInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.ApplicationUnderTest.txt_InformacionDePolizaInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
