///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Coberturas_NoEnlatado recording.
    /// </summary>
    [TestModule("2112d482-6905-442f-a447-7fb380c195aa", ModuleType.Recording, 1)]
    public partial class Coberturas_NoEnlatado : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static Coberturas_NoEnlatado instance = new Coberturas_NoEnlatado();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Coberturas_NoEnlatado()
        {
            SumaAsegurada = "400000";
            NumPolizaEmitida = "";
            ValidateNroCuenta = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Coberturas_NoEnlatado Instance
        {
            get { return instance; }
        }

#region Variables

        string _SumaAsegurada;

        /// <summary>
        /// Gets or sets the value of variable SumaAsegurada.
        /// </summary>
        [TestVariable("1ff2c81a-f8d1-4edc-8e7c-6019b60bd610")]
        public string SumaAsegurada
        {
            get { return _SumaAsegurada; }
            set { _SumaAsegurada = value; }
        }

        string _NumPolizaEmitida;

        /// <summary>
        /// Gets or sets the value of variable NumPolizaEmitida.
        /// </summary>
        [TestVariable("e87798bc-453a-4bcd-befc-7ff2e4d11de1")]
        public string NumPolizaEmitida
        {
            get { return _NumPolizaEmitida; }
            set { _NumPolizaEmitida = value; }
        }

        string _ValidateNroCuenta;

        /// <summary>
        /// Gets or sets the value of variable ValidateNroCuenta.
        /// </summary>
        [TestVariable("080a6e2e-d922-4872-8a2b-23aa47ad2105")]
        public string ValidateNroCuenta
        {
            get { return _ValidateNroCuenta; }
            set { _ValidateNroCuenta = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NombreCoberturaHogar.
        /// </summary>
        [TestVariable("d8099158-6755-4296-b7d5-77a3b4412514")]
        public string NombreCoberturaHogar
        {
            get { return repo.NombreCoberturaHogar; }
            set { repo.NombreCoberturaHogar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.OpcionCoberturaHogar' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.OpcionCoberturaHogarInfo, new RecordItemIndex(0));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.OpcionCoberturaHogar.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaInfo, new RecordItemIndex(1));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SumaAsegurada' with focus on 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada'.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAseguradaInfo, new RecordItemIndex(2));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.SumaAsegurada.PressKeys(SumaAsegurada);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.lbl_CoberturasIncendio' at Center.", repo.SURA.lbl_CoberturasIncendioInfo, new RecordItemIndex(3));
            //repo.SURA.lbl_CoberturasIncendio.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Copy_of_SumaAsegurada'", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Copy_of_SumaAseguradaInfo, new ActionTimeout(10000), new RecordItemIndex(4));
            //repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.Copy_of_SumaAseguradaInfo.WaitForNotExists(10000);
            
            //Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SURA.Cotizar' at Center.", repo.SURA.CotizarInfo, new RecordItemIndex(6));
            repo.SURA.Cotizar.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.Cotizar' at Center.", repo.SURA.CotizarInfo, new RecordItemIndex(7));
            repo.SURA.Cotizar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.Cotizacion'", repo.SURA.CotizacionInfo, new ActionTimeout(30000), new RecordItemIndex(8));
            repo.SURA.CotizacionInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(9));
            
            // Emitir Poliza
            Report.Log(ReportLevel.Info, "Section", "Emitir Poliza", new RecordItemIndex(10));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
