///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Emision
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmitirHogarNoEnlatado recording.
    /// </summary>
    [TestModule("1e8a1077-4a29-4e5d-80f7-b42f8077524c", ModuleType.Recording, 1)]
    public partial class EmitirHogarNoEnlatado : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static EmitirHogarNoEnlatado instance = new EmitirHogarNoEnlatado();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmitirHogarNoEnlatado()
        {
            NumPolizaEmitida = "";
            ValidateNroCuenta = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmitirHogarNoEnlatado Instance
        {
            get { return instance; }
        }

#region Variables

        string _NumPolizaEmitida;

        /// <summary>
        /// Gets or sets the value of variable NumPolizaEmitida.
        /// </summary>
        [TestVariable("0d130aab-dd0d-4e7a-93d9-b0562c747bac")]
        public string NumPolizaEmitida
        {
            get { return _NumPolizaEmitida; }
            set { _NumPolizaEmitida = value; }
        }

        string _ValidateNroCuenta;

        /// <summary>
        /// Gets or sets the value of variable ValidateNroCuenta.
        /// </summary>
        [TestVariable("28f4bdbb-d3ae-47a1-93b0-fa63d5ab7873")]
        public string ValidateNroCuenta
        {
            get { return _ValidateNroCuenta; }
            set { _ValidateNroCuenta = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.EmitirPoliza' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.EmitirPolizaInfo, new RecordItemIndex(0));
            repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.EmitirPoliza.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.bttn_Aceptar' at Center.", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.bttn_AceptarInfo, new RecordItemIndex(2));
            repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.bttn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.PolizaContratada'", repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.PolizaContratadaInfo, new ActionTimeout(20000), new RecordItemIndex(3));
            repo.SURA.PC.Emision.PolizaHogar.Hogar_NoEnlatado.PolizaContratadaInfo.WaitForExists(20000);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            //Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(5));
            
            // La poliza emitida es:
            Report.Log(ReportLevel.Info, "Section", "La poliza emitida es:", new RecordItemIndex(6));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SURA.Self, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.NumeroDePolizaEmitida' and assigning the part of its value captured by '[0-9]+' to variable 'NumPolizaEmitida'.", repo.SURA.NumeroDePolizaEmitidaInfo, new RecordItemIndex(8));
            NumPolizaEmitida = repo.SURA.NumeroDePolizaEmitida.Element.GetAttributeValueText("InnerText", new Regex("[0-9]+"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SURA.validate_NroCuenta' and assigning its value to variable 'ValidateNroCuenta'.", repo.SURA.validate_NroCuentaInfo, new RecordItemIndex(9));
            ValidateNroCuenta = repo.SURA.validate_NroCuenta.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "El número de poliza emitida es:", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "User", NumPolizaEmitida, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "User", "Para la cuenta:", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "User", ValidateNroCuenta, new RecordItemIndex(13));
            
            guardarNumPoliza();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
