///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////
using System.IO;
using System.Diagnostics;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Smoke.Emision
{
    public partial class RenombrarCSV
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void RenombraArchivoCSV(string Datos_Salida)
        {
            // TODO: Replace the following line with your code implementation.
            //throw new NotImplementedException();
            
            string nombrearchivo = Datos_Salida.Split('.')[0];
            //WinForms.MessageBox.Show(nombrearchivo);
          
            bool existe = File.Exists(@"C:\TEMP\Polizas\Smoke\" + Datos_Salida);
			
			try {
				if (existe)
				{
					//File.Delete(@".\Utilitarios\SalidaComando_AB.txt");
					//File.Move(@"d:\temp\faf.txt",@"d:\temp\faf_"+ System.DateTime.Now.ToString("yyyyMMdd_hhMMss") +".txt");
					
					File.Move(@"C:\TEMP\Polizas\Smoke\" + Datos_Salida,@"C:\TEMP\Polizas\Smoke\" + nombrearchivo + "_"+ System.DateTime.Now.ToString("yyyyMMdd_hhmmss") +".txt");
					Report.Success("I/O","Finalizado el proceso. Renombre Exitoso");
				}
				else{
					Report.Error("No existe el Archivo");
				}
				
			} catch (Exception e) {
				Report.Failure("I/O","No se pudo realizar la operacion\r\nError: " + e);
			}
        }

       

    }
}
