///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Smoke.Menu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuSupBuscaSoli recording.
    /// </summary>
    [TestModule("e7b1490a-73e9-41b2-ae3e-06a418dfe4bf", ModuleType.Recording, 1)]
    public partial class MenuSupBuscaSoli : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Smoke.SmokeRepository repository.
        /// </summary>
        public static global::Smoke.SmokeRepository repo = global::Smoke.SmokeRepository.Instance;

        static MenuSupBuscaSoli instance = new MenuSupBuscaSoli();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuSupBuscaSoli()
        {
            NroSoli = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuSupBuscaSoli Instance
        {
            get { return instance; }
        }

#region Variables

        string _NroSoli;

        /// <summary>
        /// Gets or sets the value of variable NroSoli.
        /// </summary>
        [TestVariable("3ca630e8-54d8-4c8a-a010-763b2d115bb1")]
        public string NroSoli
        {
            get { return _NroSoli; }
            set { _NroSoli = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("179cd022-d834-4b47-98d5-e2a34a6a6fce")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Menu.Superior.MenuSupPoliza' at CenterRight.", repo.SURA.PC.Menu.Superior.MenuSupPolizaInfo, new RecordItemIndex(0));
            repo.SURA.PC.Menu.Superior.MenuSupPoliza.Click(Location.CenterRight);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli' at Center.", repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoliInfo, new RecordItemIndex(1));
            //repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli'.", repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoliInfo, new RecordItemIndex(2));
            repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroSoli' with focus on 'SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli'.", repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoliInfo, new RecordItemIndex(3));
            repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli.PressKeys(NroSoli);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli'.", repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoliInfo, new RecordItemIndex(4));
            repo.SURA.PC.Menu.Superior.txt_SubMenuSupBuscaSoli.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SURA.PC.Txt_Validacion.txt_Cotizacion'", repo.SURA.PC.Txt_Validacion.txt_CotizacionInfo, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SURA.PC.Txt_Validacion.txt_CotizacionInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
